nodes: 
- id: haveFever
  type: question
  class: MultipleChoice
  prompt: { 'sv': 'Har du feber?' }
  choices:
  - { 'sv': 'Ja' }
  - { 'sv': 'Nej' }
  - { 'sv': 'Vet ej/kanske' }
  none_option: false

- id: bodyTemperature
  type: question
  class: QuestionFloat
  prompt: { 'sv': 'Vad är din kroppstemperatur?' }
  min_value: 20
  max_value: 55
  unit: 'ºC'

- id: canMeasureTemp
  type: question
  class: QuestionBool
  prompt: { 'sv': 'Har du möjlighet att mäta temperaturen?' }

- id: feelingWarm
  type: question
  class: QuestionBool
  prompt: { 'sv': 'Känner du dig varm?' }

- id: knownImmunoDeficiency
  type: question
  class: QuestionBool
  prompt: { 'sv': 'Har du någon känd immunbristsjukdom?' }