nodes: 
- id: constitutionalSymptoms
  type: question
  class: MultipleChoice
  variant: multi-select
  prompt: { sv: "Vilka av följande symptom stämmer in på dig?" }
  choices:
  - { sv: 'Blek, kråaktig eller blåvit hud' }
  - { sv: 'Kallsvettig' }
  - { sv: 'Orolig och rastlös' }
  - { sv: 'Andfådd eller andas snabbt och ytligt' }
  - { sv: 'Slö, dåsig och kraftlös' }
  - { sv: 'Frossa (kraftiga, okontrollerade skakningar med samtidig frysningskänsla)' }
  none_option: true
  none_prompt: { sv: "Inget av ovanstående" }

- id: notSelfSustaining
  type: question
  class: QuestionBool
  prompt: { sv: 'Upplever du svårigheter att ta hand om dig själv?' }

- id: constitutionalSymptoms
  type: evaluation
  func: |
    def evaluate(node):
      n_symptoms = sum(n.idx != 0 for n in node.answer)

      if any(n.idx == 0 for n in node.answer):
          return ConstitutionalSymptoms.NONE
      elif n_symptoms >= 3:
          return ConstitutionalSymptoms.SEVERE
      elif n_symptoms >= 1:
          return 'notSelfSustaining'
      else:
          return ConstitutionalSymptoms.UNKNOWN

- id: notSelfSustaining
  type: evaluation
  func: |
    def evaluate(node):
      return ConstitutionalSymptoms.MODERATE if node.answer else ConstitutionalSymptoms.MILD