nodes: 
- id: constitutionalSymptoms
  type: question
  class: MultipleChoice
  variant: multi-select
  prompt: { sv: "Vilka av följande symptom stämmer in på dig?" }
  choices:
  - { sv: 'Blek, kråaktig eller blåvit hud' }
  - { sv: 'Kallsvettig' }
  - { sv: 'Orolig och rastlös' }
  - { sv: 'Andfådd eller andas snabbt och ytligt' }
  - { sv: 'Slö, dåsig och kraftlös' }
  - { sv: 'Frossa (kraftiga, okontrollerade skakningar med samtidig frysningskänsla)' }
  none_option: true
  none_prompt: { sv: "Inget av ovanstående" }

- id: notSelfSustaining
  type: question
  class: QuestionBool
  prompt: { sv: 'Upplever du svårigheter att ta hand om dig själv?' }

  
  